### ISSUE TITLE
support Intellij 2021.2

### ISSUE THREAD

**Issue by mygoalistokillbill** [amibiz/ergo-keys#28]

**Comment by amibiz** [comment]
Updated the code to run on IntelliJ 2021.2 but there is a problem with keyboard shortcuts.
Opened issue https://youtrack.jetbrains.com/issue/IDEA-275511

For now, suggest to use 2021.1

**Comment by amibiz** [comment]
IntelliJ 2021.2 disabled character shortcuts by default. Because we need it for command mode, the plugin did not work.
The fix was to enable it back when new editors are created (see: f6e16903086400a5e39a2c775762699314544de7).

I have updated the plugin in JetBrains Marketplace and it should be available in a few days.

Will close this issue once the plugin is avail and working.

**Comment by amibiz** [comment]
Updated plugin for 2021.2 is available in marketplace, closing issue.
