### ISSUE TITLE
Command mode exit after run command that pop up float window.

### ISSUE THREAD

**Issue by lkyhfx** [amibiz/ergo-keys#37]
Command mode auto exit after escape from pop up float windows which open by commands that like `Shift,Shfit` or `Space, Comma`.
Is this a bug or a expected behavior?

**Comment by amibiz** [comment]
Thanks @lkyhfx  for opening the issue.

The current behavior is by design. The rational was that actions will switch automatically to _INS_ mode, saving the user an extra step. For example, if you want to _rename_ a variable when in _CMD_ mode:
1. press `A` (_Find Action_)
2. search for _rename_ action
3. when selected, switch to _INS_ mode automatically and rename the variable

For other actions, like _Go To Line_ or searching for symbols/files/classes in the search everywhere dialog, it breaks the user flow (the user is navigating code not editing).

I see two options to solve it:
1. Have a global setting that defines the default behavior when exiting the search everywhere dialog
2. Be smart and switch only when the action to be performed requires user input, like when renaming. But if the action is navigational, stay in _CMD_ mode
